#!/bin/bash

# -Zn does n distance levenshtein, ommiting n makes n = 1
ugrep -i -m 100 --color=never $1 /home/fbence/.cache/maildir-rank-addr/addressbook.tsv
# cat /home/fbence/.config/emailconfiguration/badaddress.txt
