#!/bin/bash

# sync IMAP
/home/fbence/.local/bin/mbsync -a
# fix so I can send to sourcehut
ls ~/.msmtp.queue/*msmtp | xargs -i sed -i "s/~rjarry\/aerc/u.rjarry.aerc/" {}
# send all stuck emails
/home/fbence/.local/bin/msmtp-queue -r
# update notmuch
/usr/local/bin/notmuch new
# snyc up notmuch tags
/home/fbence/.config/emailconfiguration/syncnotmuchtag.py
# set all unread emails not in mailbox to read
fd -E '*/Inbox/' '\d+\.\d+_\d+\.\w+,U=\d+:2,[^S]*$' ~/.mail -x mv {} {}S
