#!/bin/bash

/home/fbence/.local/bin/mbsync -a
ls ~/.msmtp.queue/*msmtp | xargs -i sed -i "s/~rjarry\/aerc/u.rjarry.aerc/" {}
/home/fbence/.local/bin/msmtp-queue -r
/usr/local/bin/notmuch new
/home/fbence/.config/emailconfiguration/syncnotmuchtag.py
