#!/bin/bash

# sync IMAP
/home/fbence/.local/bin/mbsync elte-fast priestoferis-fast pharmahungary-fast bence-fast 2> >(xargs -r -I{} notify-send "mbsync error" {} --urgency=critical)
# send all stuck emails
/home/fbence/.local/bin/msmtp-queue -r 2> >(xargs -r -I{} notify-send "mstmpq error" {} --urgency=critical)
# update notmuch
/usr/local/bin/notmuch new 2> >(xargs -r -I{} notify-send "notmuch error" {} --urgency=critical)
# set all unread emails not in mailbox to read
fd -E '*/Inbox/' -E '~/.mail/priestoferis' '\d+\.\d+_\d+\.\w+,U=\d+:2,[^S]*$' ~/.mail -x mv {} {}S
