#!/bin/bash

# generate addressbook
throttle maildir-rank-addr

# move any email older than 1 year from flat Archive to Archive/year
throttle --origin "mailsync-low" python3 ~/.config/emailconfiguration/rearchive.py ~/.mail/bence/Archive
throttle --origin "mailsync-low" python3 ~/.config/emailconfiguration/rearchive.py ~/.mail/bence/Sent -t ~/.mail/bence/Archive
throttle --origin "mailsync-low" mbsync bence-sent
throttle --origin "mailsync-low" mbsync bence-archive
throttle --origin "mailsync-low" python3 ~/.config/emailconfiguration/rearchive.py ~/.mail/elte/Archive
throttle --origin "mailsync-low" python3 ~/.config/emailconfiguration/rearchive.py ~/.mail/elte/Sent -t ~/.mail/elte/Archive
throttle --origin "mailsync-low" mbsync elte-sent
throttle --origin "mailsync-low" mbsync elte-archive
throttle --origin "mailsync-low" python3 ~/.config/emailconfiguration/rearchive.py ~/.mail/pharmahungary/Archive
throttle --origin "mailsync-low" python3 ~/.config/emailconfiguration/rearchive.py ~/.mail/pharmahungary/Sent -t ~/.mail/pharmahungary/Archive
throttle --origin "mailsync-low" mbsync pharmahungary-sent
throttle --origin "mailsync-low" mbsync pharmahungary-archive
# Due to how gmail's imap works, unfortunately, this does not make sense
# python3 ~/.config/emailconfiguration/rearchive.py ~/.mail/priestoferis/Archive
# python3 ~/.config/emailconfiguration/rearchive.py ~/.mail/priestoferis/Sent -t ~/.mail/priestoferis/Archive
