#!/bin/bash

# $AERC_VERSION
# $AERC_BINARY

# This could be used to enable/disable goimapnotify if it seems to eat too much:
# systemctl --user enable --now goimapnotify@bence.service
# systemctl --user enable --now goimapnotify@elte.service
# systemctl --user enable --now goimapnotify@pharmahungary.service
# systemctl --user enable --now goimapnotify@priestoferis.service

throttle --job "mbsync bence-inbox" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync bence-folders" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync bence-archive" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync bence-sent" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync bence-drafts" --job "notmuch new" --origin "hook-aerc-startup"

throttle --job "mbsync elte-inbox" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync elte-folders" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync elte-archive" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync elte-sent" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync elte-drafts" --job "notmuch new" --origin "hook-aerc-startup"

throttle --job "mbsync pharmahungary-inbox" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync pharmahungary-folders" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync pharmahungary-archive" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync pharmahungary-sent" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync pharmahungary-drafts" --job "notmuch new" --origin "hook-aerc-startup"

throttle --job "mbsync priestoferis-inbox" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync priestoferis-folders" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync priestoferis-archive" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync priestoferis-sent" --job "notmuch new" --origin "hook-aerc-startup"
throttle --job "mbsync priestoferis-drafts" --job "notmuch new" --origin "hook-aerc-startup"
