#!/bin/bash

# AERC_ACCOUNT
# AERC_FOLDER
# AERC_HOOK_ORIGIN
if [ $(hostname) = "BFERDINANDY-NB" ]; then
    if [ $AERC_ACCOUNT != "yettel" ]; then
        exit 0
    fi
fi

if [ $AERC_FOLDER == Trash ]
then
    exit 0
fi

if [ $AERC_ACCOUNT == notmuch ]
then
    if [ $(dirname $AERC_FOLDER) == "." ]
    then
        # this is a suboptimal solution for now
        accounts=$(grep '^IMAPAccount' $HOME/.config/isyncrc | sort | uniq | sed 's/IMAPAccount //' | grep -v '^yettel')
        echo "$accounts" | xargs -i  throttle --job "notmuch new" --silent-job "testinternetconnection" --job "mbsync {}-${AERC_FOLDER,,}" --job "notmuch new" --origin $AERC_HOOK_ORIGIN
        exit 0;
    else
        mbsynccmd=$(dirname ${AERC_FOLDER,,})-$(basename ${AERC_FOLDER,,})
    fi
else
    mbsynccmd=${AERC_ACCOUNT,,}-${AERC_FOLDER,,}
fi

throttle --job "notmuch new" --silent-job "testinternetconnection" --job "mbsync $mbsynccmd" --job "notmuch new" --origin $AERC_HOOK_ORIGIN
