#!/bin/bash

# AERC_ACCOUNT
# AERC_FOLDER

if [ $AERC_FOLDER == Trash ]
then
    exit 0
fi

if [ $AERC_ACCOUNT == notmuch ]
then
    if [ $(dirname $AERC_FOLDER) == "." ]
    then
        # this is a suboptimal solution for now
        mbsynccmd=all-${AERC_FOLDER,,}
    else
        mbsynccmd=$(dirname ${AERC_FOLDER,,})-$(basename ${AERC_FOLDER,,})
    fi
else
    mbsynccmd=${AERC_ACCOUNT,,}-${AERC_FOLDER,,}
fi

throttle --job "mbsync $mbsynccmd" --job "notmuch new" --origin "hook-mail-added"
