set nocompatible
set exrc
if empty(glob('~/.vim/autoload/plug.vim'))
      silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
             \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

if !exists("g:os")
    if has("win64") || has("win32") || has("win16")
        let g:os = "Windows"
    else
        let g:os = split(system('uname -a'))[-1]
    endif
endif
" leaders need to be set early because it is not dynamical
let mapleader="\<Space>"
let maplocalleader="\<Space>"
" this is needed so kitty's protocol doesn't turn the menu key into a large undo
set <F20>=57363u

source ~/.vim/configs/settings.vim
call plug#begin('~/.vim/plugged')
if !exists("g:lightweight")
    " these plugins are mostly IDE plugins that don't make sense otherwise
    " or need external dependencies and are thus irritating on systems without
    " them
    source ~/.vim/configs/coc-and-ale.vim
    source ~/.vim/configs/git.vim
    Plug 'ludovicchabant/vim-gutentags'
    Plug 'preservim/tagbar'
    " adds a context line to where you are
    Plug 'wellle/context.vim'
    " dispatch commands in the background
    Plug 'tpope/vim-dispatch'
    " run tests with e.g. Dispatch
    Plug 'vim-test/vim-test'
    " database fun
    Plug 'tpope/vim-dadbod'
    Plug 'kristijanhusak/vim-dadbod-ui'
    Plug 'kristijanhusak/vim-dadbod-completion'
    " vim debugger
    Plug 'puremourning/vimspector'
endif
" it is  in conflict with unimpaired so needs to be before
Plug 'rickhowe/diffchar.vim'
source ~/.vim/configs/floaterm.vim
source ~/.vim/configs/theme-setup.vim
" install language packs, but disable any you hand tweak
source ~/.vim/configs/vim-polyglot.vim
" extended %
Plug 'andymass/vim-matchup'
" add new targets to vim eg c2i)
Plug 'wellle/targets.vim'
" adds xml/html text objects
Plug 'kana/vim-textobj-user' | Plug 'whatyouhide/vim-textobj-xmlattr'
" tmux config syntax highlight
Plug 'whatyouhide/vim-tmux-syntax'
" syntax for kitty
Plug 'fladson/vim-kitty'
source ~/.vim/configs/i3wm-kitty-vim-tmux-navigator.vim
" command to align text (never used it yet, learn or remove)
source ~/.vim/configs/vim-easy-align.vim
" make path also when writing a new file with
Plug 'jessarcher/vim-heritage'
" open files at the last edit with some smart settings
Plug 'farmergreg/vim-lastplace'
" better surrounds than tpope's
Plug 'machakann/vim-sandwich'
" swap delimited items
source ~/.vim/configs/vim-swap.vim
" register viewing
Plug 'junegunn/vim-peekaboo'

" substitution for singular and plurals + changing the from snake_case to
" camelCase
Plug 'tpope/vim-abolish'

" auto expandtab setting
Plug 'tpope/vim-sleuth'


" n_ctrl-x/a work as expected for dates, roman numerals etc.
Plug 'tpope/vim-speeddating'
" makes speeddating repeatable
Plug 'tpope/vim-repeat'
source ~/.vim/configs/vim-obsession.vim
" simple comment facilities
Plug 'tpope/vim-commentary'
" file browser
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'Xuyuanp/nerdtree-git-plugin', { 'on': 'NERDTreeToggle' }
Plug 'tpope/vim-vinegar'
source ~/.vim/configs/vim-auto-save.vim

Plug 'honza/vim-snippets'

source ~/.vim/configs/fzf.vim

" generate tags for jumping between latex tags and others
" requires https://askubuntu.com/questions/796408/installing-and-using-universal-ctags-instead-of-exuberant-ctags
" clears searches smarter
Plug 'junegunn/vim-slash'
" visualize undo trees
Plug 'sjl/gundo.vim'


" doesn't open misspelled files
" Plug 'einfachtoll/didyoumean'
" let g:dym_use_fzf = 1
" did you mean will use fzf


" vim unimpaired might not be really needed ...
Plug 'tpope/vim-unimpaired'
" wrap unix commands
Plug 'tpope/vim-eunuch'
" asynchronous linting
" switch between multiple lines and single lines
Plug 'AndrewRadev/splitjoin.vim'

source ~/.vim/configs/movements.vim
Plug 'nanotee/zoxide.vim'
" auto switch to root dir
Plug 'airblade/vim-rooter'
"
" the below plugins are support for languages
"
" Emmet is for expanding html stuff
Plug 'mattn/emmet-vim'
" emmet might be absolutely useless and just use snippets?
let g:user_emmet_install_global = 0
autocmd FileType html,css,vue EmmetInstall

source ~/.vim/configs/writing.vim
source ~/.vim/configs/goyo.vim
Plug 'hauleth/vim-backscratch'

Plug 'pangloss/vim-javascript'
Plug 'othree/html5.vim'
Plug 'elzr/vim-json'
Plug 'jupyter-vim/jupyter-vim'
Plug 'goerz/jupytext.vim'
" PYTHON
" python code folding
Plug 'tmhedberg/SimpylFold'
" python textobjects: isn't this covered by the LSP?
Plug 'jeetsukumaran/vim-pythonsense'
Plug 'Konfekt/FastFold'
Plug 'vim-scripts/LargeFile'
" Plug 'mhinz/vim-startify'
" let g:startify_custom_header = ''

Plug 'Fymyte/mbsync.vim'
if has('nvim')
    Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }
endif
call plug#end()

doautocmd User PlugLoaded


" better escape and exiting when using arrows


" Automatically save and load folds: this is probably irritating
" autocmd BufWinLeave *.* mkview
" autocmd BufWinEnter *.* silent loadview

" ros setup
autocmd BufRead,BufNewFile *.launch setfiletype roslaunch

" Rmarkdown
autocmd BufRead,BufNewFile *.Rmd setfiletype markdown
autocmd BufRead,BufNewFile *.Rmd nnoremap <Leader>r :Dispatch R -e "rmarkdown::render('%',output_file='%.html')" <CR>



" this disable the jupyter-vim bindings
let g:jupyter_mapkeys = 0


let g:gundo_prefer_python3 = 1
