
" run vimrc found in local folder, not safe
" set exrc


if empty(glob('~/.vim/autoload/plug.vim'))
      silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
             \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

if !exists("g:os")
    if has("win64") || has("win32") || has("win16")
        let g:os = "Windows"
    else
        let g:os = split(system('uname -a'))[-1]
    endif
endif

" leaders need to be set early because it is not dynamical
let mapleader="\<Space>"
let maplocalleader="\<Space>"

let g:polyglot_disabled = ['markdown.plugin']

let g:java_ignore_javadoc = 1
let g:java_ignore_html = 1
let g:java_ignore_markdown = 1

call plug#begin()
runtime! vim-plug-configs/*.vim
if has('nvim')
    runtime! nvim-plug-configs/*.vim
endif
call plug#end()

doautocmd User PlugLoaded




