#!/bin/bash

echo -e "\033[1mrunning minimal bootstrap\033[0m"

mkdir -p ~/.local/bin

echo -e "\033[1msetting up yadm with local.class minimal\033[0m"
curl -fLo ~/.local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x ~/.local/bin/yadm
~/.local/bin/yadm clone https://github.com/ferdinandyb/dotfiles.git
~/.local/bin/yadm config --add local.class minimal
~/.local/bin/yadm sparse-checkout reapply

echo -e "\033[1minstalling fzf\033[0m"
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

echo -e "\033[1minstalling zoxide\033[0m"
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash

echo -e "\033[1minstalling vim plugins\033[0m"
vim +PlugUpdate '+qall!'

echo -e "\033[1mchange default shell to zsh\033[0m"
chsh -s $(which zsh)
