theme = "semi-native"
icons = "material-nf"


[[block]]
block = "bluetooth"
mac = "04:ED:33:CA:23:E8"
hide_disconnected = true
format = ""

[[block]]
block = "music"
format = "$combo.str(20)"
player = "spotify"

[[block]]
block = "rofication"
interval = 1
socket_path = "/tmp/rofi_notification_daemon"

[[block]]
block = "disk_space"
path="/"
info_type = "available"
alert = 10.0
warning = 15.0
format = "$percentage.eng(2)"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "$mem_used_percents.eng(1)"
format_swap = "$swap_used_percents.eng(2)"

[[block]]
block = "cpu"

[[block]]
block = "load"
interval = 5

# [[block]]
# block = "sound"

[[block]]
block = "custom"
command="~/.config/regolith3/scripts/notification"
interval=1
json=true

[[block]]
block = "time"
interval = 1
format = "%b. %d. %H:%M:%S"

[[block]]
block = "battery"
format = "$percentage|N/A"

# [[block]]
# block = "notmuch"
# query = "tag:unread"
# threshold_warning = 1
# threshold_critical = 10
