services_file: /home/fbence/.config/mailctl/services.yaml
oauth2_dir: /home/fbence/.local/var/mailctl
# This encryption method using gnupg.
# Alternatives like gnome-keyring can also be configured here.
encrypt_cmd:
  exec: gpg
  args:
    - --encrypt
    - --recipient
    - 79768ABA7C3D9B56
    - -o
decrypt_cmd:
  exec: gpg
  args:
    - --decrypt

# It might be possible to use Thunderbird's clientid/secrets: https://hg.mozilla.org/comm-central/file/tip/mailnews/base/src/OAuth2Providers.jsm
