#!/bin/sh

# Lists files changed between BASE (default: origin/HEAD) and TARGET (default: HEAD).

BASE="${1:-refs/remotes/origin/HEAD}"
TARGET="${2:-HEAD}"
MERGE_BASE=$(git merge-base --fork-point "$BASE" "$TARGET" 2>/dev/null || git merge-base "$BASE" "$TARGET")

git diff --name-only "$MERGE_BASE" ${2:+"$TARGET"}
