#!/bin/bash

# Opens files changed between BASE (default: origin/HEAD) and TARGET (default: HEAD) in nvim with fugitive diffs.

BASE="${1:-refs/remotes/origin/HEAD}"
TARGET="${2:-HEAD}"
MERGE_BASE=$(git merge-base --fork-point "$BASE" "$TARGET" 2>/dev/null || git merge-base "$BASE" "$TARGET")

set -f
IFS=$'\n'
CHANGED=($(git diff --name-only "$MERGE_BASE" ${2:+"$TARGET"}))
set +f

nvim -p "${CHANGED[@]}" \
	+"tabdo Gvdiffsplit! $MERGE_BASE" \
	+"tabdo set foldlevel=9999" \
	+"Gitsigns change_base $MERGE_BASE true"
