#!/usr/bin/env python3
import i3ipc

i3 = i3ipc.Connection()

focused = i3.get_tree().find_focused()

if focused.parent.layout == "splith":
    i3.command("move up")
    i3.command("focus parent")
    i3.command("layout tabbed")
    i3.command("focus child")
    i3.command("focus right")
elif focused.parent.layout == "splitv":
    i3.command("move left")
    i3.command("focus parent")
    i3.command("layout tabbed")
    i3.command("focus right")
elif focused.parent.layout == "tabbed":
    i3.command("layout splith")
    i3.command("move up")
    i3.command("focus parent")
    i3.command("layout tabbed")
    i3.command("focus child")
    i3.command("focus right")


